### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by jpillora** [cdipaolo/goml#1]
I'd like to learn more about machine learning and this library looks like a good place to start building something with. Are there any examples you could post to demonstrate some simple use cases?

**Comment by cdipaolo** [comment]
definitely look at the tests. They cover actual learning and saving to disk
for every method with every model (note that KMeans occasionally fails
because of the nature of random instantiation)

I have some real life examples in https://github.com/cdipaolo/goml-examples
- they aren't 100% working though. I have to fiddle with them.

I'd recommend watching at least the first like 3-4 lectures from CS229 at
Stanford if you're at all mathematically inclined. That's how I learned
(watched like 7 + reading his awesome lecture notes + watching some other
lectures)

**Comment by cdipaolo** [comment]
I should note that if you want to learn how the concepts work the math behind it is pretty necessary (like going through derivations so you actually know where the different algorithms come from.) If you just want to know how to apply the machine learning techniques in practice the models in this library are pretty much plug and play, but you should at least read the READMEs for each package and read, at least partially, through the Wikipedia page for the model (though after the intro it might get math heavy.)

[Machine Learning for Hackers](http://www.amazon.com/Machine-Learning-Hackers-Drew-Conway/dp/1449303714) ([pdf](https://github.com/wuhujun/git/blob/master/R/Machine%20Learning%20for%20Hackers.pdf)) is a book about machine learning that focuses a little more on intuition while leaving out most of the math, as well.

**Comment by jpillora** [comment]
Thanks for putting this together, much appreciated. Will see how I go and get back to you
